# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: hunterskrasek@me.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Hunter Skrasek'
author: 'Hunter Skrasek'
author_image: "/assets/images/author.jpg"
author_bio: "TODO: WRITE THIS"

paginate:	5

url: "https://hskrasek.github.io" # the base hostname & protocol for your site
baseurl: ""
permalink: pretty

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/hskrasek
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:
    desc:
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/hskrasek
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
