# Build settings

gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Hunter Skrasek"
description: > # this means to ignore newlines until "email:"
   The thoughts and opinions of Hunter Skrasek, a 22 year old web developer based out of
   Austin, Texas.

email: hunterskrasek@me.com
#blog logo
logo: "https://gravatar.com/avatar/616522697710c7a7ee8e751ee0857478.jpg?size=215"
# blog cover
cover: "/assets/images/red_doors.jpg"

name: 'Hunter Skrasek'
author: 'Hunter Skrasek'
author_image: "https://gravatar.com/avatar/616522697710c7a7ee8e751ee0857478.jpg?size=215"
author_bio: "TODO: WRITE THIS"

paginate:	5

url: "https://hunterskrasek.com" # the base hostname & protocol for your site
baseurl: ""
permalink: pretty

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/hskrasek
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:
    desc:
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/hskrasek
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
